# Site
repository: yc4ny/yc4ny.github.io
favicon: images/Y_logo.jpeg
include:
  - "_img"
# Content configuration version
version: 2

# Personal info
name: Yonwoo Choi
title: Computer Science Graduate
email: yhugestar@snu.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 00w_ony
github_username:  yc4ny
instagram_username: y0n_wo0
linkedin_username: yonwoo-choi

# About Section
# about_title: About Me
about_profile_image: images/profile_pic2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently pursuing a M.S in Computer Science at Seoul National University working in the Visual Computing Lab, where I am fortunate to be advised by <a href="https://jhugestar.github.io/">Hanbyul Joo</a>. 
  I have previously received a B.A in Computer Science from the University of Virginia and have graduated with distinction. 
  
  My research interests are in Computer Vision and Machine Learning, especially in 3D reconstruction and Human Pose Estimation. At the moment, I am interested in mixed reality pose estimation, focusing on egocentric 3D interaction recognition.
  Ultimately, I dream to build an AI system that can behave like humans in new environments and can interact with humans using a broad channel of nonverbal signals.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: Class of 2024
        sub_title: M.S Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          Affiliation: Visual Computing Lab 

          Advisor: Hanbyul Joo

          Coursework: 3D Computer Vision, Advanced Graphics, Advanced Data Mining, Mobile and Ubiquitous Computing

      - layout: left
        title: University of Virginia
        caption: Class of 2021
        sub_title: B.A Computer Science
        description: | # this will include new lines to allow paragraphs
          Coursework: Algorithms, Computer Architecture, PL for Web applications, HCI, Data Structures, Discrete Mathematics, Software Testing

  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 
        # link: boringcompany.com
        # # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stereo Reconstruction <br><br><img src="images/stereo.png" width=400 height=200 alt="stereo">
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  Stereo Reconstruction
            icon: fab fa-github
            url: https://github.com/yc4ny/Stereo-Reconstruction
        quote: >
          Stereo Camera Reconstruction using DLT, Triangulation with Non-Linear Optimization. 
        description: | # this will include new lines to allow paragraphs
          Stereo Reconstruction is an open-source project that focuses on creating a 3D reconstruction from stereo images. By leveraging the power of computer vision and deep learning techniques, the project aims to accurately estimate depth information from a pair of images captured by two cameras with a known relative position.
      - layout: top-middle
        title: Age Classifier <br><br><img src="images/age.png" width=300 height=250 alt="age">
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  Age Classifier
            icon: fab fa-github
            url: https://github.com/yc4ny/Age-Classifier
        quote: >
          Age Detection Model Trained on Pytorch
        description: | # this will include new lines to allow paragraphs
          Age Classifier is an open-source project that focuses on predicting a person's age based on facial features. Utilizing deep learning and convolutional neural networks (CNN), the project aims to create an accurate and efficient age estimation model that can be applied to various applications.
      - layout: top-middle
        title: Panorama Generator <br><br> <img src="images/panorama.png" width=400 height=200 alt="panorama">
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  Panorama Generator
            icon: fab fa-github
            url: https://github.com/yc4ny/Panorama-Generator
        quote: >
          Panorama image generator using multiple images with a single camera.
        description: | # this will include new lines to allow paragraphs
         Panorama Generator is an open-source project aimed at stitching together multiple images to create seamless, high-resolution panoramas. By employing advanced image processing and computer vision techniques, the project can combine a series of overlapping images taken from different viewpoints to produce a single, wide-angle panoramic image.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Visual Computing Lab
        # link_text: boringcompany.com
        sub_title: Graduate Researcher
        caption: November 2021 - Present
        quote: >
          The Visual Computing Laboratory aims to enable machines and robots to have human-like visual intelligence, conducting research at the intersection of computer vision, machine learning, artificial intelligence, and graphics.
        description: | # this will include new lines to allow paragraphs
            TA for 3D Computer Vision (Spring 2022)

            Research Area: 3D Reconstruction and Human Pose Estimation


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
